

server:
  port: ${APP_PORT:8070}

    
management:
  health:
    show-details: always
  metrics:
    enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics
        
       